#!/bin/bash
# Mongo Process Monitor
# Restart Mongo restore Server When It Goes Down

#timestamp:
LATEST=$(date +%y-%m-%d-%H-%M)

# restart command
RESTART="/bin/systemctl restart mongodb"

# Find mongo pid
safety_pid=$(pgrep mongod)

#check to see if mongodb has a process ID: (if null, then trigger)
if [ -z "$safety_pid" ]
then # restart mongo
  $RESTART
  echo "mongo went down, and required a restart at ${LATEST}" >> /mongo-2/logs/mongo-rebooted.log

fi
