#!/bin/bash
#this script will call the mongodb tarball from /mnt/nas/mongodump/snapshots/*.tar.gz and restore it here for testing
#it will then compare with the latest rsync value version on /mnt/nas/mongodump/dump/* which is rsynced from the same #dump file on e1, and alert if there is a difference.
#Will perform a full restore and alert if there is an import failure via e-mail

LATEST=$(date +%y-%m-%d)

#CLEANUP FOR NEXT IMPORT:
rsync /mongo-2/latest-snapshot/*.tar.gz /mongo-2/restore-points/
rm /mongo-2/latest-snapshot/*.tar.gz
rm -r /mongo-2/latest-snapshot/backup/

#remove oldest restore point [7 days]
find /mongo-2/restore-points/ -name "*.tar.gz" -type f -mtime +7 -delete
echo "cleared oldest restore point +7 days"

#Call tarball from nas and expand:
cp /mnt/nas/mongodump/latest-snapshot/mongo-snap-${LATEST}.tar.gz /mongo-2/latest-snapshot/

#expand the snapshot:
tar -xvf /mongo-2/latest-snapshot/mongo-snap-${LATEST}.tar.gz --directory=/mongo-2/latest-snapshot/

#restore mongoDB to local mongo database:
mongorestore /mongo-2/latest-snapshot/backup/mongo
